version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: insta
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: instadb
      # POSTGRES_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5430/${POSTGRES_DB}?sslmode=disable"
      
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata:
